# -*- coding: utf-8 -*-
"""Lineage_methods_Viterbi_visualize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZAMApLe-8OPQt3EC0MwOK5r3EcYe_a-d
"""

# from google.colab import drive
import os
from collections import defaultdict
from multiprocessing.pool import ThreadPool
from os import listdir
from os.path import join, basename
import numpy as np
from skimage import measure, filters
import matplotlib.pyplot as plt
from matplotlib import cm
from scipy.optimize import linear_sum_assignment
import copy
import time
import cv2
# from google.colab.patches import cv2_imshow
import random
from itertools import combinations
import pickle

ROOT = '/content/drive/'     # default for the drive
# drive.mount(ROOT)           # we mount the drive at /content/drive

# PROJECT_PATH = '/content/drive/MyDrive'

"""# 新段落"""

def main():
    folder_path: str = 'D:/viterbi linkage/dataset/'

    segmentation_folder = folder_path + 'segmentation_unet_seg//'
    save_dir = folder_path + '/save_directory_enhancement/'
    video_folder_name = folder_path + '/save_directory_enhancement/trajectory_result_video/'
    pkl_file_name: str = "ground_truth_results_dict.pkl"
    abs_save_dir = save_dir + "track_data_from_pkl/" + pkl_file_name.replace(".pkl", "")


    #settings
    track_length: int = 30
    is_save_result = True

    to_generate_series_list: list = ['S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10',
                                     'S11', 'S12', 'S13', 'S14', 'S15', 'S16', 'S17', 'S18', 'S19', 'S20']

    start_time = time.perf_counter()

    series_viterbi_result_list_dict: dict = open_track_dictionary(save_dir + pkl_file_name)

    series_viterbi_result_list_dict["S01"] = []
    cell_track_tuple_list = [(0, 0, -1), (0, 1, 0), (0, 2, 0), (2, 3, 0), (2, 4, 2), (0, 5, 2), (1, 6, 0), (0, 7, 1), (0, 8, 0), (0, 9, 0), (0, 10, 0), (0, 11, 0), (0, 12, 0), (0, 13, 0), (0, 14, 0), (1, 15, 0), (1, 16, 1), (2, 17, 1), (4, 18, 2), (3, 20, 4), (4, 21, 3), (4, 22, 4), (6, 23, 4), (9, 24, 6), (10, 25, 9), (8, 26, 10), (5, 27, 8), (5, 28, 5), (2, 29, 5), (3, 30, 2), (5, 31, 3), (2, 32, 5), (3, 33, 2), (3, 34, 3), (5, 35, 3), (6, 36, 5), (5, 37, 6), (4, 38, 5), (3, 39, 4), (3, 40, 3), (3, 41, 3), (5, 42, 3), (4, 43, 5), (1, 44, 4), (2, 45, 1), (3, 46, 2), (5, 47, 3), (3, 48, 5), (3, 49, 3), (3, 50, 3), (4, 51, 3), (3, 52, 4), (3, 53, 3), (4, 54, 3), (5, 55, 4), (3, 56, 5), (3, 57, 3), (3, 58, 3), (2, 59, 3), (2, 60, 2), (2, 61, 2), (2, 62, 2), (1, 63, 2), (1, 64, 1), (5, 65, 1), (4, 66, 5), (2, 67, 4), (5, 68, 2), (7, 69, 5), (8, 70, 7), (6, 71, 8), (6, 72, 6), (7, 73, 6), (9, 74, 7), (9, 75, 9), (8, 76, 9), (10, 77, 8), (11, 78, 10), (7, 79, 11), (8, 80, 7), (9, 82, 8), (11, 83, 9), (10, 84, 11), (11, 85, 10), (11, 86, 11), (10, 87, 11), (9, 88, 10), (5, 90, 9), (7, 91, 5), (7, 92, 7), (4, 93, 7), (2, 94, 4), (1, 95, 2), (3, 96, 1), (5, 97, 3), (8, 98, 5), (9, 99, 8), (13, 101, 9), (5, 104, 13), (7, 105, 5), (4, 106, 7), (3, 107, 4), (2, 108, 3), (8, 109, 2), (11, 110, 8), (7, 111, 11), (8, 112, 7), (7, 113, 8), (1, 114, 7), (1, 115, 1), (1, 116, 1), (5, 117, 1), (4, 118, 5), (8, 119, 4)]
    series_viterbi_result_list_dict["S01"].append(cell_track_tuple_list)

    for series, track_tuple_list_list in series_viterbi_result_list_dict.items():
        track_tuple_list_list = sorted(track_tuple_list_list)
        print("")
        for track_tuple_list in track_tuple_list_list:
            print(track_tuple_list)
            cell_tuple_id = track_tuple_list[0]
            prev_frame_idx = cell_tuple_id[1]

            print(f"series: {series}; {cell_tuple_id}: missing frame_idx: ", end='')
            for track_tuple in track_tuple_list[1:]:
                next_frame = track_tuple[1]
                if next_frame != (prev_frame_idx + 1):
                    print(f"{prev_frame_idx + 1}, ", end='')

                prev_frame_idx = next_frame
            print()

    # if pkl_file_name == "hungarian_adj_results_dict.pkl":
    #     tmp_track_tuple_list_dict = defaultdict(list)
    #     for series, track_array in series_viterbi_result_list_dict.items():
    #         track_tuple_list = track_array.tolist()
    #         tmp_track_tuple_list_dict[series] = track_tuple_list
    #
    #     series_viterbi_result_list_dict = tmp_track_tuple_list_dict


    # ground_truth_cell_dict = obtain_ground_truth_cell_dict()
    # for series in to_generate_series_list:
    #     ground_truth_cell_list = ground_truth_cell_dict[series]
    #     print("====hungarian====" + series + "==================")
    #     for cell_track_list in series_viterbi_result_list_dict[series]:
    #         is_in_gt_file = (cell_track_list[0] in ground_truth_cell_list)
    #         if is_in_gt_file:
    #             print(cell_track_list)
    #
    #     print("\n")



    # with open(abs_save_dir + ".txt", 'w') as f:
    #     f.write(f"Execution time: ---- seconds\n")
    #     # f.write("hyper_para--- ID: " + str(idx+1) + "; \n" + hyper_para.__str_newlines__())
    #     f.write("\n")
    #     for series in to_generate_series_list:
    #         f.write("======================" + str(series) + "================================")
    #         f.write("\n")
    #
    #         cell_track_list_list = sorted(series_viterbi_result_list_dict[series])
    #         for cell_track_list in cell_track_list_list:
    #             # for cell_track_list in viterbi_result_dict[series]:
    #             f.write(str(cell_track_list))
    #             f.write("\n")
    #
    #         f.write("\n\n")




    execution_time = time.perf_counter() - start_time
    print(f"Execution time: {execution_time: 0.4f} seconds")



'''opening a track dictionary from file'''
def open_track_dictionary(save_file):
    pickle_in = open(save_file, "rb")
    dictionary = pickle.load(pickle_in)

    return dictionary



def obtain_ground_truth_cell_dict():
    ground_truth_cell_dict = {}
    ground_truth_cell_dict['S01'] = [(0, 0, -1), (1, 0, -1), (3, 0, -1), (4, 0, -1)]
    ground_truth_cell_dict['S02'] = [(0, 0, -1), (1, 0, -1), (2, 0, -1), (3, 0, -1)]
    ground_truth_cell_dict['S03'] = [(6, 0, -1), (7, 0, -1)]
    ground_truth_cell_dict['S04'] = [(14, 0, -1), (15, 0, -1), (16, 0, -1), (17, 0, -1)]
    ground_truth_cell_dict['S05'] = [(0, 0, -1), (1, 0, -1), (2, 0, -1), (4, 0, -1)]
    ground_truth_cell_dict['S06'] = [(1, 0, -1), (2, 0, -1), (3, 0, -1), (4, 0, -1), (5, 0, -1)]
    ground_truth_cell_dict['S07'] = [(1, 0, -1), (2, 0, -1), (3, 0, -1), (4, 0, -1), (5, 0, -1)]
    ground_truth_cell_dict['S08'] = [(5, 0, -1), (7, 0, -1)]
    ground_truth_cell_dict['S09'] = [(7, 0, -1), (10, 0, -1)]
    ground_truth_cell_dict['S10'] = [(1, 0, -1), (2, 0, -1), (5, 0, -1)]
    ground_truth_cell_dict['S11'] = [(0, 0, -1), (1, 0, -1), (3, 0, -1)]
    ground_truth_cell_dict['S12'] = [(6, 0, -1), (7, 0, -1)]
    ground_truth_cell_dict['S13'] = [(7, 0, -1), (8, 0, -1), (10, 0, -1)]
    ground_truth_cell_dict['S14'] = [(0, 0, -1), (1, 0, -1)]
    ground_truth_cell_dict['S15'] = [(1, 0, -1), (2, 0, -1), (3, 0, -1)]
    ground_truth_cell_dict['S16'] = [(12, 0, -1), (14, 0, -1), (15, 0, -1), (20, 0, -1), (21, 0, -1)]
    ground_truth_cell_dict['S17'] = [(2, 0, -1), (5, 0, -1)]
    ground_truth_cell_dict['S18'] = [(1, 0, -1), (2, 0, -1), (3, 0, -1)]
    ground_truth_cell_dict['S19'] = [(0, 0, -1), (1, 0, -1), (2, 0, -1), (3, 0, -1)]
    ground_truth_cell_dict['S20'] = [(5, 0, -1)]

    return ground_truth_cell_dict



if __name__ == '__main__':
    main()